# Generated by Django 4.1.10 on 2023-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('postive_cash_flow', models.IntegerField()),
                ('total_savings', models.IntegerField()),
                ('total_return', models.IntegerField()),
                ('total_income', models.IntegerField()),
                ('total_expenditure', models.IntegerField()),
                ('simple_interest_earned', models.IntegerField()),
                ('advice', models.CharField(max_length=255)),
            ],
        ),
    ]
